version: "3.8"

services:
    mongo:
        image: mongo
        hostname: mongo
        volumes:
            - mongodb_data:/data/db
        ports:
            - "27017:27017"
        restart: unless-stopped
    server:
        build: ./api
        command: npm run dev
        volumes:
            - ./api/src:/app/src
            - ./api/public:/app/public
        ports:
            - "3030:3030"
        depends_on:
            - mongo
    client:
        build: ./client
        volumes:
            - /client/node_modules
            - ./client:/client
        ports:
            - "3000:3000"
        depends_on:
            - server
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        environment:
            - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017
            # - ME_CONFIG_MONGODB_SERVER='mongo'
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
            # - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            # - ME_CONFIG_MONGODB_ADMINPASSWORD=pass12345
            - ME_CONFIG_BASICAUTH_USERNAME=admin
            - ME_CONFIG_BASICAUTH_PASSWORD=admin123
        # volumes:
        #     - mongodb_data
        links: 
            - mongo
        depends_on:
            - mongo
        ports:
            - 8081:8081
        restart: unless-stopped
volumes:
    mongodb_data:
        driver: local
    # feathers_data:
    #     driver: local